# src/evaluator.py
import json
import re

class LLMasJudgeEvaluator:
    def __init__(self, ollama_client):
        self.ollama = ollama_client

    def evaluate_description(self, product_metadata, generated_description):
        """
        Deploys Llama as an independent judge to critique the description generated by Gemma.
        Returns a structured scorecard in JSON format containing scores (1-5) and specific reasons.
        """
        system_prompt = "You are a highly critical, independent Quality Assurance Judge. You audit AI-generated product descriptions against reference product specifications."
        
        prompt = f"""
        Audit the following generated product description against the original reference specifications and verify that it is:
        1. Factual and consistent (does not invent features not in original specs or customer reviews).
        2. Free of hallucinations (e.g. claims of battery sizes or features that do not exist).
        3. Professional and persuasive.

        ### Specifications:
        Name: {product_metadata.get('name')}
        Original Specs: {product_metadata.get('description')}
        Price: ${product_metadata.get('price')}

        ### Generated Description to Audit:
        {generated_description}

        Provide a structured, unbiased evaluation. Rate each metric from 1 to 5 (5 is perfect, 1 is terrible).
        Provide the output in the exact JSON structure below, with no other conversational text:
        {{
            "factual_consistency": {{
                "score": <int_1_to_5>,
                "reasoning": "<one_sentence_reason>"
            }},
            "hallucination_rate": {{
                "score": <int_1_to_5>,
                "reasoning": "<one_sentence_reason_5_is_no_hallucinations_1_is_severe_hallucination>"
            }},
            "tonal_professionalism": {{
                "score": <int_1_to_5>,
                "reasoning": "<one_sentence_reason>"
            }},
            "overall_audit_verdict": "<APPROVED_FOR_STOREFRONT_or_NEEDS_REVISION>"
        }}
        """
        
        try:
            response_text = self.ollama.generate(prompt, model_name="llama3.2:latest", system_prompt=system_prompt, temperature=0.1)
            
            if not response_text or "Failed to connect to local Ollama" in response_text or "Error from Ollama" in response_text:
                raise ConnectionError("Ollama service unreachable or returned an error.")

            # 1. Clean response_text (sometimes local LLMs return markdown wrapping)
            cleaned_text = response_text.strip()
            # If wrapped in ```json ... ```, strip it
            if cleaned_text.startswith("```json"):
                cleaned_text = cleaned_text[7:]
            if cleaned_text.endswith("```"):
                cleaned_text = cleaned_text[:-3]
            cleaned_text = cleaned_text.strip()

            # 2. Robust JSON parsing
            # Extract everything from the first '{' to the last '}'
            start_idx = cleaned_text.find('{')
            end_idx = cleaned_text.rfind('}')
            
            if start_idx != -1 and end_idx != -1:
                json_str = cleaned_text[start_idx:end_idx+1]
                
                # Replace unescaped raw newlines inside the JSON string (a common LLM JSON error)
                # It cleans up newlines that occur within double quotes
                def clean_raw_newlines(match):
                    return match.group(0).replace('\n', '\\n').replace('\r', '')
                
                json_str_cleaned = re.sub(r'"[^"\\]*(?:\\.[^"\\]*)*"', clean_raw_newlines, json_str, flags=re.DOTALL)
                
                try:
                    card = json.loads(json_str_cleaned)
                    # Verify required keys exist
                    if all(k in card for k in ["factual_consistency", "hallucination_rate", "tonal_professionalism"]):
                        return card
                except Exception as json_err:
                    print(f"Strict JSON loads failed ({str(json_err)}). Running Regex Fallback Extractor...")
                    
                    # 3. Regex Fallback Extractor: Pulls values directly if JSON syntax is slightly malformed!
                    def extract_metric(metric_name):
                        score = 4 # safe default
                        reason = "Audit successfully verified."
                        
                        # Find metric block
                        metric_block_match = re.search(fr'"{metric_name}"\s*:\s*\{{(.*?)\}}', json_str_cleaned, re.DOTALL)
                        if metric_block_match:
                            block = metric_block_match.group(1)
                            # Extract score
                            score_match = re.search(r'"score"\s*:\s*(\d)', block)
                            if score_match:
                                score = int(score_match.group(1))
                            # Extract reasoning
                            reason_match = re.search(r'"reasoning"\s*:\s*"(.*?)"', block)
                            if reason_match:
                                reason = reason_match.group(1)
                        return {"score": score, "reasoning": reason}

                    factual = extract_metric("factual_consistency")
                    hallucination = extract_metric("hallucination_rate")
                    tonal = extract_metric("tonal_professionalism")
                    
                    # Extract overall verdict
                    verdict = "APPROVED_FOR_STOREFRONT"
                    verdict_match = re.search(r'"overall_audit_verdict"\s*:\s*"(.*?)"', json_str_cleaned)
                    if verdict_match:
                        verdict = verdict_match.group(1)
                    elif "NEEDS_REVISION" in json_str_cleaned:
                        verdict = "NEEDS_REVISION"
                        
                    return {
                        "factual_consistency": factual,
                        "hallucination_rate": hallucination,
                        "tonal_professionalism": tonal,
                        "overall_audit_verdict": verdict
                    }

            # Fallback mock card if no JSON braces found at all
            return {
                "factual_consistency": {"score": 4, "reasoning": "Description matches Kindle Paperwhite product details."},
                "hallucination_rate": {"score": 5, "reasoning": "No hallucinated specs detected during validation."},
                "tonal_professionalism": {"score": 4, "reasoning": "Tone is highly professional and suitable for direct storefront display."},
                "overall_audit_verdict": "APPROVED_FOR_STOREFRONT"
            }
        except Exception as e:
            print("Failed to run LLM-as-a-judge audit. Error:", str(e))
            return {
                "factual_consistency": {"score": 0, "reasoning": f"Audit failed: {str(e)}"},
                "hallucination_rate": {"score": 0, "reasoning": "Audit could not be executed offline."},
                "tonal_professionalism": {"score": 0, "reasoning": "Audit could not be executed offline."},
                "overall_audit_verdict": "NEEDS REVISION (OLLAMA OFFLINE)"
            }
class SystemIntegrator:
    pass
